; PlatformIO Project Configuration File
; Docs: https://docs.platformio.org/page/projectconf.html

; 全局配置段（放在 env 段外面）：配置项目级的源码根目录
[platformio]
src_dir = .  ; 全局指定源码扫描根目录为项目根目录（.）
include_dir = . ;全局指定头文件扫描根目录为项目根目录（.）

[env:genericSTM32F103C8]
; Target: STM32F103C8T6 + CMSIS
platform = ststm32
board = genericSTM32F103C8
framework = cmsis

; Upload/Debug: ST-Link
debug_tool = stlink
upload_protocol = stlink
upload_port = *STLink*

; Serial monitor (Windows COM auto match)
monitor_port = COM*
monitor_speed = 115200
monitor_encoding = utf-8

; Improve local library dependency scanning (FreeRTOS/StdPeriph)
lib_ldf_mode = deep+

build_src_filter = +<*> -<.git/> -<.vscode/> -<README.md> -<*.ini>  ; 包含所有文件，排除无关目录

; Build options
build_flags =
    ; Core 层（核心配置/头文件/源码）
    -ICore/Inc
    ; FreeRTOS 实时系统
    -IFreeRTOS/Inc
    ; 外设功能模块（LED/串口）
    -IModule/led
    -IModule/usart
    -IModule/delay
    ; 用户代码
    -IUser

    -DUSE_STDPERIPH_DRIVER
    -DSTM32F10X_MD
    -specs=nano.specs
