; PlatformIO Project Configuration File
; Docs: https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
; Target: STM32F103C8T6 + CMSIS
platform = ststm32
board = genericSTM32F103C8
framework = cmsis

; Upload/Debug: ST-Link
debug_tool = stlink
upload_protocol = stlink
upload_port = *STLink*

; Serial monitor (Windows COM auto match)
monitor_port = COM*
monitor_speed = 115200
monitor_encoding = utf-8

; Improve local library dependency scanning (FreeRTOS/StdPeriph)
lib_ldf_mode = deep+

; Build options
build_flags =
    -Iinclude
    -Isrc/utility
    -DUSE_STDPERIPH_DRIVER
    -DSTM32F10X_MD
    -specs=nano.specs
